# Configuration for evaluation.

defaults:
  - base
  - _self_

data:
  train_csv_path: null
  val_csv_path: ${oc.env:BASE_PATH}/data/finetune_dataset/metadata_test.csv
  mask_lig_seq: True
  min_t: 0.01
  num_t: 200
  num_eval_samples: null
  num_repeat_per_eval_sample: 16

  # Add Gaussian noise to center position.
  center_pos_noise: True
  center_pos_noise_std: 2.0

experiment:
  name: eval_gen
  
  eval_batch_size: ${data.num_repeat_per_eval_sample}
  num_loader_workers: 4
  use_ddp : True
  use_gpu: True
  num_gpus: 8

  warm_start: ${experiment.eval_only}
  warm_start_ckpt_path: ${experiment.eval_ckpt_path}
  reset_training: False
  use_warm_start_conf: False

  # Evaluation.
  eval_only: True
  eval_ckpt_path: ${oc.env:BASE_PATH}/experiments/checkpoints/diffpepbuilder_v1.pth
  eval_dir: ${oc.env:BASE_PATH}/runs/eval_outputs
  noise_scale: 1.0
  seq_temperature: 0.1

